// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7-DQcYh4V-K3gPqrv92-QR71d6FP9Q0',
    appId: '1:575502485664:web:037f0d82a64c0a2709a1c5',
    messagingSenderId: '575502485664',
    projectId: 'mp-college-app',
    authDomain: 'mp-college-app.firebaseapp.com',
    storageBucket: 'mp-college-app.appspot.com',
    measurementId: 'G-1E0XNL2SDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUwKkx2p28RtakZQBtmyGl_Z2pnNEMvYU',
    appId: '1:575502485664:android:20cd4e34031f59d609a1c5',
    messagingSenderId: '575502485664',
    projectId: 'mp-college-app',
    storageBucket: 'mp-college-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2IA1Ef1h2QST3G_8TjSOHH_EsEi752Ws',
    appId: '1:575502485664:ios:37027b91a468aba309a1c5',
    messagingSenderId: '575502485664',
    projectId: 'mp-college-app',
    storageBucket: 'mp-college-app.appspot.com',
    iosBundleId: 'com.example.collegeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2IA1Ef1h2QST3G_8TjSOHH_EsEi752Ws',
    appId: '1:575502485664:ios:3eb705e4c4414c5709a1c5',
    messagingSenderId: '575502485664',
    projectId: 'mp-college-app',
    storageBucket: 'mp-college-app.appspot.com',
    iosBundleId: 'com.example.collegeApp.RunnerTests',
  );
}
